name: influx_alerter
description: A simple client to alert from influx to different sources when values are outside of a specific range
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '^3.0.0'

dependencies:
  args: 2.4.2
  pedantic: 1.11.1
  yaml: 3.1.2
  influxdb_client: 2.9.0
  logging:
  teledart: 0.5.6
  mailer:
  path:
